[phases.install]
nixPkgs = ['python38', 'gcc9']
aptPkgs = ['build-essential', 'libpixman-1-dev', 'librsvg2-dev']
nixLibs = ['libjpeg', 'giflib', 'fontconfig', 'cairo', 'pango', 'pixman']

[phases.build]
cmds = ["yarn run build-prod"]

[start]
cmd = "yarn run start-built"