[phases.install]
nixPkgs = ['python38', 'gcc9']
aptPkgs = ['libpixman-1-dev', 'libcairo2-dev', 'libpango1.0-dev', 'libgif-dev']
nixLibs = ['libjpeg']

[phases.build]
cmds = ["yarn run build-prod"]

[start]
cmd = "yarn run start-built"